baseURL = "https://squirrelq.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Topwise Brewing"
theme = "hallo-hugo-master"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Topwise Brewing"

[params]

	gtm = "GTM-W3BTHD2"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:topwisebrewing@gmail.com"

    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/topwisebrewing/"

    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://www.facebook.com/Topwise-Brewing-109624477833155/"
      
